### ISSUE TITLE
pre-trained weights problem

### ISSUE THREAD

**Issue by ZheningHuang** [Lornatang/SSRGAN#3]
Hi Changyu, great work! One question regarding the pre-trained weight. I have the following problems when downloading the pre-trained weights. Could you please check if that is the same on your side? 

```
$ cd weights/
$ python3 download_weights.py

```
Traceback (most recent call last):
  File "C:\Users\fibe-cdt\Desktop\github\SSRGAN\weights\download_weights.py", line 14, in <module>
    from ssrgan.models import pmigan
ModuleNotFoundError: No module named 'ssrgan'
(SuperR)

**Comment by Lornatang** [comment]
I .. unupload this weights
